FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
python3-tk \
&& rm -rf /var/lib/apt/lists/*

ENV DISPLAY=host.docker.internal:0

COPY notepad.py /app/notepad.py

WORKDIR /app

CMD ["python3", "notepad.py"]

